#!/bin/bash

# Install RNAVIEW
# based on https://github.com/fjossinet/RNArtistCore/blob/fda9898e796d234290dceded7ca0cc67e08fea69/Dockerfile
wget -qO RNAVIEW.tar.gz "http://ndbserver.rutgers.edu/ndbmodule/services/download/RNAVIEW.tar.gz"
tar -xzvf RNAVIEW.tar.gz
cd RNAVIEW/
make && make clean
cd ~
rm RNAVIEW.tar.gz

# set environmental variable
export RNAVIEW="$HOME/RNAVIEW"
export PATH=$RNAVIEW/bin:$PATH

# retrieve rnartistcore and build  Kotlin library to describe and plot RNA secondary structures
git clone https://github.com/fjossinet/RNArtistCore.git
cd RNArtistCore/
git pull
mvn clean package

